spring:
  application:
    name: cli
  main:
    banner-mode: off
  shell:
    command:
      version:
        enabled: true
        show-build-time: true
        show-build-version: true
        show-git-branch: true
        show-git-short-commit-id: true
        show-git-commit-time: true
logging:
  pattern:
    console:
  file:
    name: 'cympl-cli.log'
